### ISSUE TITLE
部署项目时出错

### ISSUE THREAD

**Issue by faithererer** [hua1995116/react-resume-site#49]
```shell
F:\WorkSpace\resume\react-resume-site>yarn install && yarn start
yarn install v1.22.22
[1/4] Resolving packages...
error Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by faithererer** [comment]
添加命令解决
```
yarn config set "strict-ssl" false -g
```
